# spring profile: prod|dev
profile: dev

# Set the connection to the DB
jdbc:
    drone:
        driver: com.mysql.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/gts"
        #username: gts2
        #password: opengts
        username: root
        password: root

http:
    port: 8888
    adminPort: 9091
    
rss:
    type: "rss_2.0"
    title: "RSS feed by Auke Team"
    description: "RSS feed by Auke Team"
    language: "en"
    copyright: "Copyright by Auke Team"
    
server: 
    domain: http://89.221.242.66:8080/drone
    url: http://89.221.242.66:8888/rss/
    #domain: http://localhost:8080/drone
    #url: http://localhost:8888/rss/

track:
    maxActive: 10
